# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[󰣇 ❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[󰣇 ❯](bold red)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
vimcmd_symbol = '[ ❮](bold green)'
vimcmd_replace_one_symbol = '[ ❮](bold purple)'
vimcmd_replace_symbol = '[ ❮](bold purple)'
vimcmd_visual_symbol = '[ ❮](bold yellow)'

[username]
show_always = true
format = '[ $user]($style) '

[hostname]
ssh_only = false
format = '[ $hostname]($style)'

[directory]
format = '[  $path]($style)[$read_only]($read_only_style) '
